version: '3.8'

services:
  app:
    build: ./src
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis-db
    depends_on:
      - redis-db

  redis-db:
    image: redis:7-alpine # Imagem base leve e focada em desempenho operacional
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data # Atende a exigência de persistência via volume nomeado do segundo serviço

volumes:
  redis_data: # Declaração obrigatória do escopo global do volume nomeado