version: '3.8'

services:
  app:
    build: ./src
    ports:
      - "3000:3000"
    environment:
      - DB_USER=postgres
      - DB_HOST=db
      - DB_NAME=meuapp
      - DB_PASSWORD=senha123
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=senha123
      - POSTGRES_DB=meuapp
    volumes:
      - pgdata:/var/lib/postgresql/data # Volume nomeado: dados sobrevivem ao container [cite: 65, 66]

volumes:
  pgdata: # Declaração obrigatória do volume nomeado [cite: 68]